### ISSUE TITLE
Support for EP3241

### ISSUE THREAD

**Issue by poldim** [TillFleisch/ESPHome-Philips-Smart-Coffee#44]
Looking to add support for this model.  Happy to provide what I can.  Previous discussion in [this issue](https://github.com/TillFleisch/ESPHome-Philips-Smart-Coffee/issues/7#issuecomment-1983887267).

Updated video, hopefully of the correct direction:
Log: https://drive.google.com/file/d/1zgdv9gLjzWldKlpgCwNJoKhxN2zFkwBv/view?usp=sharing
Video of what I pressed when: https://photos.app.goo.gl/amxp7EkJXCvxmE3P7

**Comment by TillFleisch** [comment]
The log files contain the same content as in [this comment](https://github.com/TillFleisch/ESPHome-Philips-Smart-Coffee/issues/7#issuecomment-1982002287) (Messages from the display to the mainboard). Since we are currently interested in figuring out why the status sensor is not updating properly, messages from the mainboard to the display are required (as the sensor state is determined based on these messages).

Unlike the messages originating from the display, like:
>```
>D5 55 00 01 03 00 12 00 00 00 10 21 [idle]
>D5 55 00 01 03 00 12 02 00 00 08 3A [espresso]
>D5 55 00 01 03 00 12 00 02 00 08 38 [bean]
>D5 55 00 01 03 00 12 00 08 00 3A 03 [milk]
>D5 55 00 01 03 00 12 00 04 00 21 12 [size]
>D5 55 00 01 03 00 12 08 00 00 38 0B [coffee]
>D5 55 00 01 03 00 12 20 00 00 21 00 [americano]
>D5 55 00 01 03 00 12 04 00 00 20 16 [cappuccino]
>D5 55 00 01 03 00 12 10 00 00 08 31 [latte]
>D5 55 00 01 03 00 12 00 01 00 1C 2D [hot water]
>D5 55 00 01 03 00 12 00 10 00 0C 21 [aqua clean]
>D5 55 00 01 03 00 12 00 20 00 29 20 [calc clean]
>D5 55 00 01 03 00 12 01 00 00 1C 2C [power off]
>```
(recorded display-to-mainboard messages; [source](https://github.com/TillFleisch/ESPHome-Philips-Smart-Coffee/issues/7#issuecomment-1983887267))

The messages originating from the display are longer, as described in [protocol.md#messages-from-the-mainboard-to-the-display](https://github.com/TillFleisch/ESPHome-Philips-Smart-Coffee/blob/main/protocol.md#messages-from-the-mainboard-to-the-display).


@poldim, can you take a look at #41, as it's very similar to a part of this issue (idle state not detected on some `EP2220` machines)? Maybe a similar, simple fix is possible for your machine.
