### ISSUE TITLE
Add support for 3300 series

### ISSUE THREAD

**Issue by wss2** [TillFleisch/ESPHome-Philips-Smart-Coffee#85]
Add support for 3300 series most command are similar but not all.
I can turn it off but not turn it on. I use model: EP_3246

List of working buttons:
POWER_OFF not ON
PLAY_PAUSE work
MAKE_ESPRESSO work
MAKE_COFFEE work
SELECT_HOT_WATER is STEAM

The status seems read well

With a 2200 it worked great.

I can help in some way by reading the codes independently?

**Comment by TillFleisch** [comment]
There is already a discussion regarding a EP33xx machine ([see here, EP3321/40 in particular](https://github.com/TillFleisch/ESPHome-Philips-Smart-Coffee/discussions/71)). Let's continue this discussion over in #71 under the assumption that all EP33xx machines use the same commands. If this turns out not to be the case, we can open another discussion regarding your specific model-nr.
